# Generated by Django 4.2.7 on 2023-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('translation', models.CharField(max_length=300)),
                ('part_of_speech', models.CharField(choices=[('1', 'noun'), ('2', 'verb'), ('3', 'adverb'), ('4', 'adjective'), ('5', 'pronoun'), ('6', 'preposition'), ('7', 'conjunction'), ('8', 'interjection'), ('9', 'determiner')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
