# Generated by Django 4.2.7 on 2023-11-06 21:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_progress_card_progress_word_delete_vocabulary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('word', 'user')},
        ),
    ]
