# Generated by Django 4.2.7 on 2023-11-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSentence',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.progress')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sentence')),
            ],
            bases=('app.progress',),
        ),
    ]
