# Generated by Django 4.2.7 on 2023-11-21 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_rename_time_slots_streak_learning_times_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectionPorgress',
            new_name='LectionProgress',
        ),
    ]
