# Generated by Django 4.1 on 2023-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_lectionporgress_lectionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionprogress',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
