# Generated by Django 4.1 on 2023-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lectionprogress_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='lection',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='lection',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
