# Generated by Django 4.2.7 on 2023-11-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_timestamp_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressperhour',
            name='hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timestamp'),
        ),
    ]
