# Generated by Django 4.1 on 2023-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sentence_lection_word_lection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionprogress',
            name='tmp_lection_prg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
