# Generated by Django 4.2.7 on 2023-11-23 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_progressperhour_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='learning_times',
        ),
        migrations.AlterUniqueTogether(
            name='progressperhour',
            unique_together={('user', 'hour')},
        ),
        migrations.AddField(
            model_name='streak',
            name='learning_times',
            field=models.ManyToManyField(to='app.timestamp'),
        ),
    ]
