# Generated by Django 4.2.7 on 2023-11-23 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_remove_streak_learning_times_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressperhour',
            old_name='hour',
            new_name='time_stamp',
        ),
        migrations.AlterUniqueTogether(
            name='progressperhour',
            unique_together={('user', 'time_stamp')},
        ),
    ]
