# Generated by Django 4.1 on 2023-11-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lectionprogress_tmp_lection_prg'),
        ('app', '0015_rename_streak_streaks'),
    ]

    operations = [
    ]
