# Generated by Django 4.2.7 on 2023-11-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_progressperhour_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressperhour',
            options={'ordering': ('time_stamp',)},
        ),
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ('date', 'hour')},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('lection', 'word')},
        ),
    ]
