# Generated by Django 4.1 on 2023-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_progressperhour_options_and_more'),
        ('app', '0018_alter_word_options'),
    ]

    operations = [
    ]
