# Generated by Django 4.2.7 on 2023-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_usersettings_options_usersettings_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_time_learned',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
